name: UpT

on:
  workflow_dispatch:
  repository_dispatch:
    types: [UpT]
jobs:
    run:
      runs-on: ubuntu-20.04
      timeout-minutes: 20
      steps:
      - uses: actions/checkout@v3
      - name: run
        run: bash estat.sh
      env:
        CL: ${{secrets.CL}}
        DOWNLOADS: ${{secrets.DOWNLOADS}}
        REQUIREMENT: ${{secrets.REQUIREMENT}}
        RUNNER: ${{secrets.RUNNER}}
